### ISSUE TITLE
Color Code Only

### ISSUE THREAD

**Issue by aroon9002ahmed** [seballot/spectrum#10]
is there any option to get color code only?
for exmple if you select black color value will be "black" how i can get it as "#000000"

**Comment by GianlucaScarciolla** [comment]
Hello @aroon9002ahmed !

You can simple use the option `preferredFormat: "hex",`

You can find more about it here: [Preferred Format](https://seballot.github.io/spectrum/#options-preferredFormat) :-)

**Comment by seballot** [comment]
Thanks @GianlucaScarciolla
