### ISSUE TITLE
TypeScript Support

### ISSUE THREAD

**Issue by Damo1155** [seballot/spectrum#12]
Whilst the library works wonders (even managed to get this into Knockout easily) it's missing support for TypeScript (TS).

I've gotten around this by extending the jQuery TS interface, not doing so would mean the following which is bad practice.

`(<any>$(ele)).spectrum(options))`

Additionally, I've created a fairly primitive interface (e.g. **_index.d.ts_**) to allow access to the callbacks in a semi type safe way. 

Saving others this hassle would be great so wondering if it would be possible to get a fully defined TypeScript interface which allows access to the libraries features without having to create them ourselves or go against good practices

**Comment by seballot** [comment]
Hi @Damo1155, I have no time for this, but if you want to do it I will be happy to include it in the repo !

**Comment by seballot** [comment]
no more opened issue, well done @fabienwnklr !! 

please ping me if you want me to publish a new version on npm (or I can give you access to spectrum package on npm, as you wish)

**Comment by fabienwnklr** [comment]
then lot of issues are outdated and fixed from , you can publish yes :) as you want, but i think i'm more disposable, give me acces when you have time :) @seballot
