### ISSUE TITLE
No release on Github, yet released on NPM and Yarnpkg

### ISSUE THREAD

**Issue by Rikijs** [seballot/spectrum#15]
Releases are not synced on `github`, 'NPM' and `yarnpkg`. 

On `yarnpkg.com` newest version is: 2.0.5!
On `NPM` newest version is: 2.0.5!
Yet
On `github.com` newest version is: __2.0.0__!

Please sync new versions.

**Comment by seballot** [comment]
Hi @Rikijs, what do you mean by "On github.com" ?

**Comment by Rikijs** [comment]
Hi, @seballot!
No new versions in `releases` on `Github`
(https://github.com/seballot/spectrum/releases)

**Comment by seballot** [comment]
ah ok :) done

**Comment by Rikijs** [comment]
Hi, @seballot!
Unfortunately `latest relese` is still version __2.0.0__.
But i see that you added a `tag` for version __2.0.5__.
Thanks for changes!

**Comment by Rikijs** [comment]
Thank you!
