### ISSUE TITLE
Multiple pickers and knockout

### ISSUE THREAD

**Issue by FFRainman** [seballot/spectrum#19]
I'm using multiple pickers on the same page combined with knockout when selecting a color in one of the pickers and closing it by clicking another colorpicker, the value doesn't get updated to the knockout variable.

Steps to reproduce:
1. Click first textfield
2. Select a color, value in textbox will change, don't click choose
3. Click the second textfield and select a color
4. The knockout variable bound to the first textfield won't be updated

**Comment by seballot** [comment]
Hi, this is a framework related issue, you should probably wrap the color picket in a component, see #11
