### ISSUE TITLE
pyScss compiler failing because url() function parameter not in quotes

### ISSUE THREAD

**Issue by caspii** [seballot/spectrum#21]
The [Sass compiler ](https://github.com/Kronuz/pyScss)I use in my python webapp doesn't like `url(data:image/png...`. 

Can I create a PR to change this to `url('data:image/png...'` (i.e. include quotes)?

**Comment by seballot** [comment]
sure !

**Comment by seballot** [comment]
Ok it's done

**Comment by caspii** [comment]
Thanks! Sorry I put off fixing it myself for too long 😔
