### ISSUE TITLE
problem in chrome for android

### ISSUE THREAD

**Issue by lukexp** [seballot/spectrum#22]
is having a problem in chrome for android, I click on the input the first time and it works. If I try again it closes on its own, I can't open it anymore because it opens and closes.

**Comment by lukexp** [comment]
tested it on 3 android phones, in all 3 it has given the problem, apparently it is doubling the touchstart and click events. As a solution for me I changed the 370 line, I changed from toggle to the show.

**Comment by seballot** [comment]
Hi @lukexp ! Thanks for the test, you could create a pull request with your change please?

**Comment by lukexp** [comment]
I'm sorry, I don't know how to create pull request. I just changed line 370 of the javascript file https://github.com/seballot/spectrum/blob/master/src/spectrum.js . As a side effect, it no longer closes by clicking on the input, just clicking outside the container. I changed it from "toggle ();" for "show();"

**Comment by seballot** [comment]
Ok thanks, the fix seems good enough for me, it's pushed and deployed with new version 2.0.6
