### ISSUE TITLE
Update icons to SVG

### ISSUE THREAD

**Issue by bjarnef** [seballot/spectrum#24]
Currently the icons used for e.g. clear is bitmap images. Any reason not to use SVG background images these days?
https://caniuse.com/?search=background%20svg

https://github.com/seballot/spectrum/blob/master/src/spectrum.css#L43
https://github.com/seballot/spectrum/blob/master/src/spectrum.css#L531-L543

For example the clear icon looks blurry.
![image](https://user-images.githubusercontent.com/2919859/116587704-00f1f480-a91b-11eb-9634-5e063a10cbeb.png)

An example of using SVG as background image:
https://css-tricks.com/probably-dont-base64-svg/

Just a quick test using icon from https://icomoon.io/app/#/select and https://yoksel.github.io/url-encoder/ to generate CSS for background image with SVG.

![image](https://user-images.githubusercontent.com/2919859/116588999-7dd19e00-a91c-11eb-82db-b8f41bf9567c.png)

```
background-image: url(data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 1024 1024'%3E%3Cg%3E%3Cpath class='cursor-pointer' mi-d='M512 854q140 0 241-101t101-241q0-114-74-210l-478 478q96 74 210 74zM170 512q0 114 74 210l478-478q-96-74-210-74-140 0-241 101t-101 241zM512 86q176 0 301 125t125 301-125 301-301 125-301-125-125-301 125-301 301-125z' mi-fill='inherit' mi-stroke='inherit' mi-stroke-width='inherit' mi-stroke-linejoin='inherit' mi-stroke-linecap='inherit' mi-stroke-miterlimit='inherit' mi-opacity='1' ng-click='selectPath($index)' mi-absorb-clicks='' d='M512 854q140 0 241-101t101-241q0-114-74-210l-478 478q96 74 210 74zM170 512q0 114 74 210l478-478q-96-74-210-74-140 0-241 101t-101 241zM512 86q176 0 301 125t125 301-125 301-301 125-301-125-125-301 125-301 301-125z' fill='inherit' stroke='inherit' stroke-width='inherit' stroke-linejoin='inherit' stroke-linecap='inherit' stroke-miterlimit='inherit' opacity='1'%3E%3C/path%3E%3C/g%3E%3C/svg%3E);
```

**Comment by seballot** [comment]
Hi ! Yep good idea, if you want to create a pull request with the change I will merge it

thanks !

**Comment by bjarnef** [comment]
Fixed in https://github.com/seballot/spectrum/pull/26
