### ISSUE TITLE
toHex8String returns alpha before rgb resulting in wrong colour

### ISSUE THREAD

**Issue by William-Wildridge** [seballot/spectrum#31]
https://github.com/seballot/spectrum/blob/5021146c1f1fd7597f6e056505944cf035549013/src/spectrum.js#L1813

The function expects the alpha variable to be last in the list, but it is currently first. This results in the returned hex8 string with the alpha digits first rather than last.

**Comment by fabienwnklr** [comment]
i'm note sure to understand, you mean the order in array is wrong ? 

alpha in last, that it ?

```js
var hex = [
    pad2(mathRound(r).toString(16)),
    pad2(mathRound(g).toString(16)),
    pad2(mathRound(b).toString(16)),
    pad2(convertDecimalToHex(a))
];
```

**Comment by William-Wildridge** [comment]
That's right : )

**Comment by fabienwnklr** [comment]
i see, if you want and if u have time u can make a PR, otherwise i fix un next week :)
