### ISSUE TITLE
Changing 'allowEmpty' option after initializing doesn't apply change

### ISSUE THREAD

**Issue by NHerw** [seballot/spectrum#37]
Hi, this is my first Issue on github, so please excuse any beginner mistakes :)

I tried to change the `allowEmpty` option using `$("#picker-id").spectrum("option", "allowEmpty", true)`.
`opts[allowEmpty]` gets changed to `true` correctly, but `allowEmpty` doesn't. 

Adding this statement: 

```
if (optionName === "allowEmpty") {
   allowEmpty = opts.allowEmpty;
}
```
to this function:

https://github.com/seballot/spectrum/blob/78f49ef5e3df3b4a80d0c887f8e2dc5365da6b0f/dist/spectrum.js#L1005-L1019

 at least made it possible to apply an empty color value:

This doesn't fix the problem entirely but I can't figure out how to fix it further.

Thanks!

**Comment by fabienwnklr** [comment]
Thanks you for reporting. Fixed !

i close this issue :)
