### ISSUE TITLE
CSS Deprecation Warnings when using SCSS

### ISSUE THREAD

**Issue by Damo1155** [seballot/spectrum#5]
Just installed the colour picker via YARN and whilst what I've found isn't a massive issue at the moment it could be in the future.

I reported a problem on a different library a number of months ago (link below to the issue) where an SCSS file wasn't shipped with the dist file. This causes issues as referencing CSS files directly in an SCSS file type is deprecated and likely to be removed in the future.

[Zebra Datepicker Issue 157](https://github.com/stefangabos/Zebra_Datepicker/issues/157)

As part of the DIST for the plugin, would it be possible to also ship it with the SCSS so we (and others) can appease our task runners.

**Comment by seballot** [comment]
Hi @Damo1155 !
I just included the scss file in dist (which is just a copy of the css file, changing extension). Is that what you wanted?

https://github.com/seballot/spectrum/tree/master/dist

**Comment by Damo1155** [comment]
That's exactly what I need. Thanks for the quick turnaround!
