### ISSUE TITLE
Update to TinyColor v1.4.1

### ISSUE THREAD

**Issue by marioagarcia** [seballot/spectrum#6]
I am in need of using the `tohex8String()` in TinyColor but the version that is currently in this library does not have support for Chrome's new adoption of the W3C draft on CSS colour where the last two digits are the ones that reflect the alpha. You can find more info on the issue on here. They include the fix for this in v1.4.1.

https://github.com/bgrins/TinyColor/issues/82

Is this something feasible? I can create a pull request. Also, is there a reason why you copied and pasted TinyColor instead of requiring it via npm?

Thank you

**Comment by seballot** [comment]
Hi ! yes please if you want to do a pull request, using npm package instead, and with the last version, it would be a pleasure !

**Comment by marioagarcia** [comment]
Ok sounds good, I will work on that

**Comment by seballot** [comment]
Thanks !
