### ISSUE TITLE
Initial colour not set in palette only mode

### ISSUE THREAD

**Issue by philja8** [seballot/spectrum#7]
Hi there

Firstly, thanks heaps for your work building this library!

I just wanted to raise a possible bug when using the palette only mode (showPaletteOnly: true) and specifying a custom palette.  It happens when I set an initial colour as the value of the input element.  It works fine when not using palette only mode.

I have created a jsfiddle to illustrate the issue - https://jsfiddle.net/philanderson/uk875gwe/.

For now I am able to work around this by explicitly setting the colour after initialising the colour picker e.g. $('#showPaletteOnly').spectrum('set', '#78c3ff').  Would be great if it is possible to fix though.

Thanks again

**Comment by seballot** [comment]
Hello @philja8 ! I just tested your jsfiddle and for me it works okay

![spectrum](https://user-images.githubusercontent.com/17404254/94687322-64d42080-032c-11eb-9e4f-589aa0783962.gif)

What browser are you using?

**Comment by philja8** [comment]
Hi @seballot 

Thanks for getting back to me so quickly.

I'm testing this in Chrome at present but... in your test above you are actually demonstrating the issue because both input elements in the HTML have the same initial value of `#78c3ff` but the one with `showPaletteOnly: true` is ignoring that value and defaulting to the first colour in the palette `#fe453b`.

I think both input elements should be showing the same initial colour of `#78c3ff`.

**Comment by seballot** [comment]
oh I see !

But I'm not sure it's an issue. for me, as we have palette only, it's normal that the input color must be on the color proposed by the palette, no? not sure

**Comment by philja8** [comment]
I think the issue is that we are specifying an initial colour in the input element so, because that colour exists in the palette, Spectrum should recognise that and automatically set the selected colour to the one I am specifying in the input value (like it does for `showPaletteOnly: false`).

If my input element had no initial value (e.g. `<input type="text" id="Colour" value="" />`) then the palette should propose the default colour because I hadn't specified one.  The same would be the case if the initial value I specified didn't exist in the palette - then show the default colour.

If you take an example where we save a users form input (including the colour) to a database and, later, the user attempts to edit that form... we should be able to show the colour the user selected and saved previously by setting the initial value on the input element e.g. `<input type="text" id="Colour" value="#78c3ff" />`.

As mentioned, this is working great when not in palette only mode, it just becomes a problem with `showPaletteOnly: true`.

**Comment by seballot** [comment]
Ok, why not, but does not seems high priority to me, and I'm focus on other stuff right now. Also I did not write this lib, I just made it looks nicer, so I will no be faster than any other dev to do this change. So if you want to have a try and do a pull request, it would be very welcomed !
