### ISSUE TITLE
Jquery Click event/delegate defined on the "Choose" Button not firing

### ISSUE THREAD

**Issue by rajarshi-basu** [seballot/spectrum#8]
Hello,

I want to write a custom JQuery event handler for the "Choose" Button. However, it seems that such an event isn't firing.
I have created a fiddle to explain the issue better: [Link to Fiddle](https://jsfiddle.net/x87oq6Lh/)

Click on the Open Picker button, then click on Choose.
We are expecting the message inside alert to be displayed, but then nothing happens.

P.S. : This is an awesome library

Thank You.

**Comment by hervesoulie** [comment]
Hi,
I agree that events for the cancel et save buttons would be great.

@Veldoran : Looking at your fiddle, the main issue is that the button does not exist when you are initializing the handler. The init should be done once the picker has been inserted into the page (likely in the "show" event)
